# Generated by Django 2.1.8 on 2025-11-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UmsteigenApp', '0021_station_db_station_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='bvg_pdf',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
