# Generated by Django 2.1.8 on 2025-11-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UmsteigenApp', '0022_station_bvg_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='bvg_levelguide',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
